# Generated by Django 3.1.7 on 2021-09-26 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hwtgenml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='test_captions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='boostrapmodel',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boostrapmodel',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='TestCaptionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='TestImages')),
                ('recognize_text', models.TextField(default='')),
                ('caption', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hwtgenml.testcaption')),
            ],
        ),
    ]
